version: '3'

services:
  traefikk:
    # Aller sur http://localhost:8080/api/rawdata pour visionner si traefik fonctionne et ce qu'il configure
    # http://localhost:8080/dashboard pour voir le dashboard de traefik et vérifier que tout fonctionne
    image: traefik:v2.3
    container_name: traefikk
    restart: always
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api/.docker/cert.pem:/certs:ro
      - ./api/.docker/traefik:/etc/traefik:ro
    labels:
      - traefik.http.routers.traefik_test.rule=Host(`traefik.docker.localhost`)
      - traefik.http.services.traefik_test.loadbalancer.server.port=8080
      - traefik.http.middlewares.tls-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.tls-redirectscheme.redirectscheme.permanent=true
    networks:
      - reverse_proxy

  api:
    # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#customization
    image: webdevops/php-nginx-dev:7.4
    container_name: api
    depends_on:
      - mysql
    volumes:
      - ./api/:/rootapp
      - ./api/.docker/nginx/docker-nginx.conf:/opt/docker/etc/nginx/vhost.conf
      - ./api/.docker/cert.pem:/certs:ro
    working_dir: /rootapp
    env_file:
      - ./api/.env
    environment:
      # PHP config
      # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#environment-variables
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: "on"
      PHP_MEMORY_LIMIT: 1024M
      PHP_MAX_EXECUTION_TIME: 86400
      PHP_REQUEST_TERMINATE_TIMEOUT: 86400
      PHP_POST_MAX_SIZE: 50M
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_OPCACHE_REVALIDATE_FREQ: 0
      php.xdebug.var_display_max_depth: 10
      php.xdebug.var_display_max_data: 2048
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.docker.localhost`)
      - traefik.http.routers.api.entrypoints=http
      - traefik.http.routers.api-secure.rule=Host(`api.docker.localhost`)
      - traefik.http.routers.api-secure.tls=true
      - traefik.http.routers.api-secure.entrypoints=https
      - traefik.docker.network=traefik_default
      - traefik.port=444
    networks:
      - reverse_proxy

  client:
    container_name: client
    # Use a static website hosting service in production
    # See https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true # https://github.com/facebook/create-react-app/issues/8688
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app:rw,cached
      - /app/node_modules
    ports:
      - "3001:3001"
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`front.docker.localhost`)
      - traefik.http.routers.client.entrypoints=http
      - traefik.docker.network=traefik_default
      - traefik.port=3001
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - reverse_proxy

  admin:
    container_name: admin
    # Use a static website hosting service in production
    # See https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment
    build:
      context: ./admin
      dockerfile: Dockerfile
    stdin_open: true # https://github.com/facebook/create-react-app/issues/8688
    env_file:
      - ./admin/.env
    volumes:
      - ./admin:/app:rw,cached
      - /app/node_modules
    ports:
      - "3003:3003"
    labels:
      - traefik.enable=true
      - traefik.http.routers.admin.rule=Host(`admin.docker.localhost`)
      - traefik.http.routers.admin.entrypoints=http
      - traefik.docker.network=traefik_default
      - traefik.port=3003
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - reverse_proxy

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=tototo
      - MYSQL_DATABASE=api
    volumes:
      - db_data:/var/lib/mysql
      - ./api/.docker/mysql:/etc/mysql/conf.d"
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external:
      name: traefik_default

volumes:
  db_data:
