doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        server_version: '5.7'
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            UserDomain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/User'
                prefix: 'App\Domain\User'
            BookDomain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/Book'
                prefix: 'App\Domain\Book'
