nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            origin_regex: true
            allow_origin: [ '^http://admin.docker.localhost' ]
            allow_headers: [ 'X-Custom-Auth', 'Content-Type' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600
            hosts: [ '^api\.' ]
        '^/api/':
            origin_regex: true
            allow_origin: [ '^http://admin.docker.localhost' ] # You probably want to change this regex to match your real domain
            allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
            allow_headers: [ 'Content-Type', 'Authorization', 'X-Custom-Auth' ]
            expose_headers: [ 'Link' ]
            max_age: 3600
